/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as CertificationRouteImport } from './routes/certification'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HospitalRouteImport } from './routes/hospital'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VoicebridgeRouteImport } from './routes/voicebridge'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnLessonRouteImport } from './routes/learn.$lesson'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationRoute = CertificationRouteImport.update({
  id: '/certification',
  path: '/certification',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalRoute = HospitalRouteImport.update({
  id: '/hospital',
  path: '/hospital',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VoicebridgeRoute = VoicebridgeRouteImport.update({
  id: '/voicebridge',
  path: '/voicebridge',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnLessonRoute = LearnLessonRouteImport.update({
  id: '/learn/$lesson',
  path: '/learn/$lesson',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/assessment': typeof AssessmentRoute
  '/certification': typeof CertificationRoute
  '/dashboard': typeof DashboardRoute
  '/hospital': typeof HospitalRoute
  '/login': typeof LoginRoute
  '/practice': typeof PracticeRoute
  '/signup': typeof SignupRoute
  '/voicebridge': typeof VoicebridgeRoute
  '/learn/$lesson': typeof LearnLessonRoute
  '/learn/': typeof LearnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/assessment': typeof AssessmentRoute
  '/certification': typeof CertificationRoute
  '/dashboard': typeof DashboardRoute
  '/hospital': typeof HospitalRoute
  '/login': typeof LoginRoute
  '/practice': typeof PracticeRoute
  '/signup': typeof SignupRoute
  '/voicebridge': typeof VoicebridgeRoute
  '/learn/$lesson': typeof LearnLessonRoute
  '/learn': typeof LearnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/assessment': typeof AssessmentRoute
  '/certification': typeof CertificationRoute
  '/dashboard': typeof DashboardRoute
  '/hospital': typeof HospitalRoute
  '/login': typeof LoginRoute
  '/practice': typeof PracticeRoute
  '/signup': typeof SignupRoute
  '/voicebridge': typeof VoicebridgeRoute
  '/learn/$lesson': typeof LearnLessonRoute
  '/learn/': typeof LearnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/assessment'
    | '/certification'
    | '/dashboard'
    | '/hospital'
    | '/login'
    | '/practice'
    | '/signup'
    | '/voicebridge'
    | '/learn/$lesson'
    | '/learn/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/assessment'
    | '/certification'
    | '/dashboard'
    | '/hospital'
    | '/login'
    | '/practice'
    | '/signup'
    | '/voicebridge'
    | '/learn/$lesson'
    | '/learn'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility'
    | '/assessment'
    | '/certification'
    | '/dashboard'
    | '/hospital'
    | '/login'
    | '/practice'
    | '/signup'
    | '/voicebridge'
    | '/learn/$lesson'
    | '/learn/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AssessmentRoute: typeof AssessmentRoute
  CertificationRoute: typeof CertificationRoute
  DashboardRoute: typeof DashboardRoute
  HospitalRoute: typeof HospitalRoute
  LoginRoute: typeof LoginRoute
  PracticeRoute: typeof PracticeRoute
  SignupRoute: typeof SignupRoute
  VoicebridgeRoute: typeof VoicebridgeRoute
  LearnLessonRoute: typeof LearnLessonRoute
  LearnIndexRoute: typeof LearnIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certification': {
      id: '/certification'
      path: '/certification'
      fullPath: '/certification'
      preLoaderRoute: typeof CertificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital': {
      id: '/hospital'
      path: '/hospital'
      fullPath: '/hospital'
      preLoaderRoute: typeof HospitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voicebridge': {
      id: '/voicebridge'
      path: '/voicebridge'
      fullPath: '/voicebridge'
      preLoaderRoute: typeof VoicebridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$lesson': {
      id: '/learn/$lesson'
      path: '/learn/$lesson'
      fullPath: '/learn/$lesson'
      preLoaderRoute: typeof LearnLessonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  AssessmentRoute: AssessmentRoute,
  CertificationRoute: CertificationRoute,
  DashboardRoute: DashboardRoute,
  HospitalRoute: HospitalRoute,
  LoginRoute: LoginRoute,
  PracticeRoute: PracticeRoute,
  SignupRoute: SignupRoute,
  VoicebridgeRoute: VoicebridgeRoute,
  LearnLessonRoute: LearnLessonRoute,
  LearnIndexRoute: LearnIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
